#!/usr/bin/env python

import subprocess
import optparse
import re

def get_arguments():
    parser = optparse.OptionParser()
    parser.add_option("-i", "--interface", dest="interface", help="Interface to change mac address")
    parser.add_option("-m", "--mac", dest="mac_address", help="Address to change mac address")
    (options, arguments) = parser.parse_args()
    if not options.interface:
        parser.error("[-] Please enter the interface. Use --help to get help")

    elif not options.mac_address:
        parser.error("[-] Please enter the mac address. Use --help to get help")

    return options

def mac_changer(interface, mac_address):
    subprocess.call(["ifconfig", interface, "down"])
    subprocess.call(["ifconfig", interface, "hw", "ether", mac_address])
    subprocess.call(["ifconfig", interface, "up"])

def get_current_mac(interface):
    ifconfig_result = subprocess.check_output(["ifconfig", interface])
    search_value = re.search(r"\w\w:\w\w:\w\w:\w\w:\w\w:\w\w", ifconfig_result)
    if search_value:
        return search_value.group(0)
    else:
        print("[-] Could not read mac address")


options = get_arguments()
current_mac = get_current_mac(options.interface)
print("current_mac = " + str(current_mac))

mac_changer(options.interface, options.mac_address)
current_mac = get_current_mac(options.interface)
if current_mac == options.mac_address:
    print("[+] Mac Address is successfully changed to " + current_mac )
else:
    print("[-] Mac address did not get changed")
